import os
import glob
import re
import pandas as pd
import sys

def parse_responses(file: str):
    """
    Function to parse the responses generated by LLMs for the name association task
    """
    def extract_last_number(text: str):
        """
        Extract the last number in the response, to get the class and ethnicity association
        """
        if pd.isna(text):
            return None
        numbers = re.findall(r"\d+", str(text))
        if not numbers:
            return None
        return int(numbers[-1]) if 1 <= int(numbers[-1]) <= 7 else None
    
    def extract_age(text: SystemError):
        """
        Extract the age association (only if one number is present in the response, to exclude age ranges)
        """
        if pd.isna(text):
            return None
        ages = re.findall(r"\d+", str(text))
        if len(ages) == 1:
            return ages[0]
        else:
            return None

    def gender_from_response(text: str):
        """
        Extract gender association by looking at most gender-related matches
        """
        if pd.isna(text):
            return None
        t = str(text).lower()
        man_count   = t.count("man")   + t.count("jongen")
        vrouw_count = t.count("vrouw") + t.count("meisje")

        if man_count > vrouw_count:
            return "man"
        elif vrouw_count > man_count:
            return "vrouw"
        else:
            return None

    # Read csv file
    df = pd.read_csv(file, sep=None, engine="python")

    # Create new columns for parsed response
    for col in ["pattern_match"]:
        if col not in df.columns:
            df[col] = None

    # Parse association responses
    class_rows  = df["test"] == "Class"
    eth_rows    = df["test"] == "Ethnicity"
    mask_gender = df["test"].str.lower() == "gender"
    mask_age    = df["test"].str.lower() == "age"
    df.loc[class_rows,  "pattern_match"] = df.loc[class_rows,  "response"].apply(extract_last_number)
    df.loc[eth_rows,    "pattern_match"] = df.loc[eth_rows,    "response"].apply(extract_last_number)
    df.loc[mask_gender, "pattern_match"] = df.loc[mask_gender, "response"].apply(gender_from_response)
    df.loc[mask_age,    "pattern_match"] = df.loc[mask_age,    "response"].apply(extract_age)

    return df

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python pattern_matching_responses.py <folder>")
        sys.exit(1)

    folder = sys.argv[1]  # Folder with csv files with LLM responses

    # Select all files
    csv_files = glob.glob(os.path.join(folder, "*.csv"))
    tsv_files = glob.glob(os.path.join(folder, "*.tsv"))
    files = csv_files + tsv_files

    for file in files:
        # Create path for saving new file
        base = os.path.basename(file)
        name, ext = os.path.splitext(base)
        new_name = f"{name}_pm{ext}"
        new_path = os.path.join(folder, new_name)

        # Run pattern matching and save new file
        df_file = parse_responses(file)
        df_file.to_csv(new_path, sep="\t", index=False)
